rabbit:
    image: rabbitmq:3.6.0
redis:
    image: redis:3.0.7
crawler1:
    image: munch-crawler
    command: crawler
        - rabbit
        - redis
director:
    image: munch-director
    command: director
    links:
        - rabbit
        - redis
